"""
Unit and integration tests for ShinerAI Phase 4 Model Explainability pipeline and service.
Validates generation of global and local SHAP explanations, saved figures, reports, and service behavior.
"""

import json
from pathlib import Path
import joblib
import pandas as pd
import pytest

from backend.explainability import ExplainabilityService


FIGURES_DIR = Path("results/figures/explainability")
REPORTS_DIR = Path("results/reports/explainability")


def test_explainability_artifacts_exist():
    """Verify all 6 PNG figures and 4 reports were generated by the explainability pipeline."""
    expected_figures = [
        "global_feature_importance_xgb_config_c.png",
        "global_feature_importance_rf_config_c.png",
        "local_explanation_safe_xgb_config_c.png",
        "local_explanation_at_risk_xgb_config_c.png",
        "local_explanation_safe_rf_config_c.png",
        "local_explanation_at_risk_rf_config_c.png",
    ]
    for fig_name in expected_figures:
        fig_path = FIGURES_DIR / fig_name
        assert fig_path.exists(), f"Missing explainability figure: {fig_path}"
        assert fig_path.stat().st_size > 5000, f"Figure file suspiciously small: {fig_path}"

    expected_reports = [
        "global_importance_xgb_config_c.csv",
        "global_importance_rf_config_c.csv",
        "local_explanations_summary.json",
        "explainability_report.md",
    ]
    for rep_name in expected_reports:
        rep_path = REPORTS_DIR / rep_name
        assert rep_path.exists(), f"Missing explainability report: {rep_path}"
        assert rep_path.stat().st_size > 0, f"Report file is empty: {rep_path}"


def test_global_importance_csv_structure():
    """Verify global importance CSV files contain 11 features with current_do as rank 1."""
    for model_name in ["xgb", "rf"]:
        csv_path = REPORTS_DIR / f"global_importance_{model_name}_config_c.csv"
        df = pd.read_csv(csv_path)
        assert len(df) == 11, f"Expected 11 features in {csv_path}, found {len(df)}"
        assert "feature" in df.columns
        assert "mean_abs_shap" in df.columns
        assert "rank" in df.columns
        # current_do should be rank 1
        assert df.iloc[0]["feature"] == "current_do"
        assert df.iloc[0]["rank"] == 1


def test_local_explanations_json_content():
    """Verify local_explanations_summary.json contains both test cases and models."""
    json_path = REPORTS_DIR / "local_explanations_summary.json"
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    assert "safe" in data
    assert "at_risk" in data

    for case_key in ["safe", "at_risk"]:
        case_data = data[case_key]
        assert "pond_id" in case_data
        assert "prediction_timestamp" in case_data
        assert "xgboost" in case_data
        assert "random_forest" in case_data

        for model_key in ["xgboost", "random_forest"]:
            model_res = case_data[model_key]
            assert "risk_probability" in model_res
            assert "predicted_label" in model_res
            assert "feature_contributions" in model_res
            assert len(model_res["feature_contributions"]) == 11
            for feat in model_res["feature_contributions"]:
                assert "feature" in feat
                assert "value" in feat
                assert "shap_value" in feat
                assert feat["direction"] in ["toward_AT_RISK", "toward_SAFE"]


def test_explainability_service_execution():
    """Verify ExplainabilityService handles single prediction instance correctly."""
    model = joblib.load("models/xgboost_config_c.joblib")
    service = ExplainabilityService(model)

    dummy_payload = {
        "pond_id": "test_pond",
        "prediction_timestamp": "2026-01-26T03:30:00",
        "features": {
            "current_do": 3.84,
            "hour_of_day": 3.0,
            "minute_of_day": 210.0,
            "do_t_minus_15": 4.05,
            "do_t_minus_30": 4.49,
            "do_t_minus_45": 4.67,
            "do_t_minus_60": 4.69,
            "do_t_minus_75": 4.73,
            "do_t_minus_90": 4.85,
            "do_t_minus_105": 5.00,
            "do_t_minus_120": 5.02,
        },
    }

    result = service.explain(dummy_payload)
    assert "base_value" in result
    assert "feature_contributions" in result
    assert len(result["feature_contributions"]) == 11
    assert "top_risk_drivers" in result
    assert "top_safe_drivers" in result
    assert "scientific_note" in result
    assert "not prove biological causality" in result["scientific_note"]
